export const POSITIONS = [
  { id: 1, name: 'Профессор', code: 'PROF' },
  { id: 2, name: 'Доцент', code: 'DOCENT' },
  { id: 3, name: 'Старший преподаватель', code: 'SENIOR_LECTURER' },
  { id: 4, name: 'Преподаватель', code: 'LECTURER' },
];

export const SUBJECTS = [
  { id: 1, name: 'Основы программирования', hours: 120 },
  { id: 2, name: 'Алгоритмы и структуры данных', hours: 140 },
  { id: 3, name: 'Веб-разработка', hours: 100 },
  { id: 4, name: 'Базы данных', hours: 80 },
  { id: 5, name: 'Машинное обучение', hours: 60 },
  { id: 6, name: 'Разработка мобильных приложений', hours: 70 },
  { id: 7, name: 'Разработка сетевых приложений', hours: 50 },
  { id: 8, name: 'Компьютерные сети', hours: 40 },
];

export const WORKLOAD_TYPES = [
  { id: 1, name: 'Лекционные занятия' },
  { id: 2, name: 'Практические задания' },
  { id: 3, name: 'Лабораторные занятия' },
  { id: 4, name: 'Экзамены' },
  { id: 5, name: 'Зачеты' },
];

export const WORKLOAD_NORMS = [
  // Лекции
  { typeId: 1, year: '2025-2026', rate: 1.0, hours: 200, positionId: 1 },
  { typeId: 1, year: '2025-2026', rate: 0.75, hours: 150, positionId: 2 },
  { typeId: 1, year: '2025-2026', rate: 0.5, hours: 100, positionId: 3 },

  // Практические занятия
  { typeId: 2, year: '2025-2026', rate: 1.0, hours: 150, positionId: 1 },
  { typeId: 2, year: '2025-2026', rate: 0.75, hours: 110, positionId: 2 },
  { typeId: 2, year: '2025-2026', rate: 0.5, hours: 70, positionId: 3 },

  // Лабораторные занятия
  { typeId: 3, year: '2025-2026', rate: 1.0, hours: 100, positionId: 1 },
  { typeId: 3, year: '2025-2026', rate: 0.75, hours: 80, positionId: 2 },
  { typeId: 3, year: '2025-2026', rate: 0.5, hours: 60, positionId: 3 },

  // Экзамены
  { typeId: 4, year: '2025-2026', rate: 1.0, hours: 50, positionId: 1 },
  { typeId: 4, year: '2025-2026', rate: 0.75, hours: 40, positionId: 2 },

  // Зачеты
  { typeId: 5, year: '2025-2026', rate: 1.0, hours: 60, positionId: 1 },
  { typeId: 5, year: '2025-2026', rate: 0.5, hours: 30, positionId: 3 },
];

export const WORKLOAD_PLANS = [
  { teacherId: 1, year: '2025-2026', plannedHours: 220 },
  { teacherId: 2, year: '2025-2026', plannedHours: 180 },
  { teacherId: 3, year: '2025-2026', plannedHours: 150 },
  { teacherId: 4, year: '2025-2026', plannedHours: 200 },
  { teacherId: 5, year: '2025-2026', plannedHours: 120 },
  { teacherId: 6, year: '2025-2026', plannedHours: 160 },
  { teacherId: 7, year: '2025-2026', plannedHours: 190 },
  { teacherId: 8, year: '2025-2026', plannedHours: 140 },
  { teacherId: 9, year: '2025-2026', plannedHours: 210 },
  { teacherId: 10, year: '2025-2026', plannedHours: 175 },
];

export const WORKLOADS = [
  // Преподаватель 1
  {
    id: 1,
    teacherId: 1,
    typeId: 1,
    subjectId: 1,
    hours: 40,
    year: '2025-2026',
  }, // Лекции
  {
    id: 2,
    teacherId: 2,
    typeId: 1,
    subjectId: 1,
    hours: 20,
    year: '2025-2026',
  }, // Лекции
  {
    id: 3,
    teacherId: 1,
    typeId: 2,
    subjectId: 1,
    hours: 30,
    year: '2025-2026',
  }, // Практики
  {
    id: 4,
    teacherId: 1,
    typeId: 3,
    subjectId: 1,
    hours: 20,
    year: '2025-2026',
  }, // Лабы
  {
    id: 5,
    teacherId: 1,
    typeId: 4,
    subjectId: 1,
    hours: 10,
    year: '2025-2026',
  }, // экзамены
  {
    id: 6,
    teacherId: 1,
    typeId: 5,
    subjectId: 1,
    hours: 20,
    year: '2025-2026',
  }, // зачеты

  // Преподаватель 2
  {
    id: 7,
    teacherId: 2,
    typeId: 1,
    subjectId: 2,
    hours: 35,
    year: '2025-2026',
  },
  {
    id: 8,
    teacherId: 2,
    typeId: 2,
    subjectId: 2,
    hours: 25,
    year: '2024-2025',
  },
  {
    id: 9,
    teacherId: 2,
    typeId: 3,
    subjectId: 1,
    hours: 15,
    year: '2024-2025',
  },
  {
    id: 10,
    teacherId: 2,
    typeId: 4,
    subjectId: 1,
    hours: 5,
    year: '2024-2025',
  },
  {
    id: 11,
    teacherId: 2,
    typeId: 5,
    subjectId: 1,
    hours: 15,
    year: '2024-2025',
  },

  // Преподаватель 3
  {
    id: 12,
    teacherId: 3,
    typeId: 1,
    subjectId: 3,
    hours: 20,
    year: '2024-2025',
  },
  {
    id: 13,
    teacherId: 3,
    typeId: 2,
    subjectId: 5,
    hours: 20,
    year: '2024-2025',
  },
  {
    id: 14,
    teacherId: 3,
    typeId: 3,
    subjectId: 6,
    hours: 20,
    year: '2024-2025',
  },
  {
    id: 15,
    teacherId: 3,
    typeId: 4,
    subjectId: 7,
    hours: 10,
    year: '2024-2025',
  },
  {
    id: 16,
    teacherId: 3,
    typeId: 5,
    subjectId: 8,
    hours: 12,
    year: '2023-2024',
  },
];

export const USERS = [
  // Admin
  {
    id: 1,
    username: 'admin',
    email: 'admin@example.com',
    password: 'admin123',
    isAdmin: true,
  },

  // Teachers
  {
    id: 2,
    username: 'teacher1',
    email: 'teacher1@example.com',
    password: 'teacher123',
    isAdmin: false,
  },
  {
    id: 3,
    username: 'teacher2',
    email: 'teacher2@example.com',
    password: '12121212',
    isAdmin: false,
  },
  {
    id: 4,
    username: 'teacher3',
    email: 'teacher3@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 5,
    username: 'teacher4',
    email: 'teacher4@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 6,
    username: 'teacher5',
    email: 'teacher5@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 7,
    username: 'teacher6',
    email: 'teacher6@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 8,
    username: 'teacher7',
    email: 'teacher7@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 9,
    username: 'teacher8',
    email: 'teacher8@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 10,
    username: 'teacher9',
    email: 'teacher9@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 11,
    username: 'teacher10',
    email: 'teacher10@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 12,
    username: 'teacher11',
    email: 'teacher11@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 13,
    username: 'teacher12',
    email: 'teacher12@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 14,
    username: 'teacher13',
    email: 'teacher13@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 15,
    username: 'teacher14',
    email: 'teacher14@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 16,
    username: 'teacher15',
    email: 'teacher15@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 17,
    username: 'teacher16',
    email: 'teacher16@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 18,
    username: 'teacher17',
    email: 'teacher17@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 19,
    username: 'teacher18',
    email: 'teacher18@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 20,
    username: 'teacher19',
    email: 'teacher19@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
  {
    id: 21,
    username: 'teacher20',
    email: 'teacher20@example.com',
    password: 'PASSWORD_HASH',
    isAdmin: false,
  },
];

export const TEACHERS = [
  {
    id: 1,
    userId: 2,
    firstName: 'Иван',
    lastName: 'Петров',
    patronymic: 'Сергеевич',
    positionId: 2,
    rate: 1.0,
  },
  {
    id: 2,
    userId: 3,
    firstName: 'Мария',
    lastName: 'Кузнецова',
    patronymic: 'Игоревна',
    positionId: 3,
    rate: 0.75,
  },
  {
    id: 3,
    userId: 4,
    firstName: 'Алексей',
    lastName: 'Соколов',
    patronymic: 'Андреевич',
    positionId: 4,
    rate: 1.0,
  },
  {
    id: 4,
    userId: 5,
    firstName: 'Ольга',
    lastName: 'Васильева',
    patronymic: 'Павловна',
    positionId: 1,
    rate: 1.0,
  },
  {
    id: 5,
    userId: 6,
    firstName: 'Дмитрий',
    lastName: 'Новиков',
    patronymic: 'Олегович',
    positionId: 2,
    rate: 0.5,
  },
  {
    id: 6,
    userId: 7,
    firstName: 'Елена',
    lastName: 'Федорова',
    patronymic: 'Викторовна',
    positionId: 3,
    rate: 1.0,
  },
  {
    id: 7,
    userId: 8,
    firstName: 'Кирилл',
    lastName: 'Морозов',
    patronymic: 'Геннадьевич',
    positionId: 4,
    rate: 1.0,
  },
  {
    id: 8,
    userId: 9,
    firstName: 'Татьяна',
    lastName: 'Семенова',
    patronymic: 'Александровна',
    positionId: 2,
    rate: 0.25,
  },
  {
    id: 9,
    userId: 10,
    firstName: 'Павел',
    lastName: 'Егоров',
    patronymic: 'Михайлович',
    positionId: 4,
    rate: 1.0,
  },
  {
    id: 10,
    userId: 11,
    firstName: 'Светлана',
    lastName: 'Данилова',
    patronymic: 'Юрьевна',
    positionId: 3,
    rate: 1.0,
  },
  {
    id: 11,
    userId: 12,
    firstName: 'Игорь',
    lastName: 'Орлов',
    patronymic: 'Владимирович',
    positionId: 1,
    rate: 1.0,
  },
  {
    id: 12,
    userId: 13,
    firstName: 'Юлия',
    lastName: 'Макарова',
    patronymic: 'Артемовна',
    positionId: 2,
    rate: 0.5,
  },
  {
    id: 13,
    userId: 14,
    firstName: 'Сергей',
    lastName: 'Беляев',
    patronymic: 'Иванович',
    positionId: 4,
    rate: 1.0,
  },
  {
    id: 14,
    userId: 15,
    firstName: 'Анна',
    lastName: 'Громова',
    patronymic: 'Петровна',
    positionId: 4,
    rate: 0.75,
  },
  {
    id: 15,
    userId: 16,
    firstName: 'Максим',
    lastName: 'Мельников',
    patronymic: 'Романович',
    positionId: 3,
    rate: 1.0,
  },
  {
    id: 16,
    userId: 17,
    firstName: 'Виктория',
    lastName: 'Трофимова',
    patronymic: 'Ильинична',
    positionId: 1,
    rate: 1.0,
  },
  {
    id: 17,
    userId: 18,
    firstName: 'Андрей',
    lastName: 'Жуков',
    patronymic: 'Семенович',
    positionId: 2,
    rate: 0.5,
  },
  {
    id: 18,
    userId: 19,
    firstName: 'Наталья',
    lastName: 'Кириллова',
    patronymic: 'Вадимовна',
    positionId: 3,
    rate: 1.0,
  },
  {
    id: 19,
    userId: 20,
    firstName: 'Георгий',
    lastName: 'Панин',
    patronymic: 'Константинович',
    positionId: 4,
    rate: 1.0,
  },
  {
    id: 20,
    userId: 21,
    firstName: 'Екатерина',
    lastName: 'Борисова',
    patronymic: 'Станиславовна',
    positionId: 3,
    rate: 0.75,
  },
];
